name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  financial-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: financial
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Go test
        run: go test ./...
      - name: Docker compose config
        run: docker compose -f docker-compose.prod.yml config
      - name: Kustomize render
        run: |
          sudo snap install kubectl --classic
          kubectl kustomize deploy/k8s

